apiVersion: batch/v1beta1
kind: CronJob
metaData:
  name: reporting-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      containers:
        - name: reporting-tool
          image: reporting-tool
      restartPolicy: Never