apiVersion: extensions/v1beta1
kind: ingress
metaData:
  name: ingress-wear-watch
spec:
  rules:
  - host: wear.online.com
    http:
      paths:
      - backend:
          serviceName: wear-service
          servicePort: 80
  - host: watch.online.com
    http:
      paths:
      - backend:
        serviceName: watch-service
        servicePort: 80
