apiVersion: batch/v1
kind: job
metaData:
  name: match-add-job
spec:
  completions: 3
  parallelism: 3
  template:
    spec:
      containers:
        - name: match-add
          image: ubuntu
          command: ['expr', '3', '+', '2']
      restartPolicy: Never