apiVersion: v1
kind: ReplicationController
metadata:
  name: Myapp-RC
  labels:
    app: Myapp
    type: micro service
spec:
  template:
    metadata:
      name: user-service-pod
      labels:
        app: user-microservice
        purpose: Horizontal scale
    spec:
      containers:
        - name: kubernetes-setup-service
          image: kubernetes-setup-service/demo:latest

  replicas: 3

